name: smart_windows_app
description: "Environment monitor for Smart Citizen devices"
publish_to: 'none'
version: 0.1.3

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  http: ^1.2.0
  rxdart: ^0.27.7
  fl_chart: ^0.66.2
  flutter_local_notifications: ^16.3.2
  aad_oauth: "^1.0.1"
  jwt_decoder: ^2.0.1
  is_first_run: ^1.0.0
  flutter_app_badger: ^1.5.0
  fluttertoast: ^8.2.4
  sign_in_button: ^3.2.0
  settings_ui: ^2.0.2
  flutter_xlider: ^3.5.0
  collection: ^1.18.0
  overlay_support: ^2.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - /assets/images/
